# Generated by Django 2.0 on 2018-01-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PSHTTResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect', models.BooleanField(verbose_name='Redirect')),
                ('validHTTPS', models.BooleanField(verbose_name='Valid HTTPS')),
                ('defaultHTTPS', models.BooleanField(verbose_name='Default HTTPS')),
                ('downgradeHTTPS', models.BooleanField(verbose_name='Downgrades HTTPS')),
                ('strictlyHTTPS', models.BooleanField(verbose_name='Strictly Forces HTTPS')),
                ('badChain', models.BooleanField(verbose_name='Bad Chain')),
                ('badHostname', models.BooleanField(verbose_name='Bad Hostname')),
                ('expiredCert', models.BooleanField(verbose_name='Expired Cert')),
                ('selfSignedCert', models.BooleanField(verbose_name='Self-signed Cert')),
                ('HSTS', models.BooleanField(verbose_name='HSTS')),
                ('supportHTTPS', models.BooleanField(verbose_name='Support HTTPS')),
                ('enforceHTTPS', models.BooleanField(verbose_name='Enforce HTTPS')),
                ('strongHSTS', models.BooleanField(verbose_name='Strong HSTS')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='SSLResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSLv2', models.BooleanField(verbose_name='SSLv2')),
                ('SSLv3', models.BooleanField(verbose_name='SSLv3')),
                ('TLSv10', models.BooleanField(verbose_name='TLSv1.0')),
                ('TLSv11', models.BooleanField(verbose_name='TLSv1.1')),
                ('TLSv12', models.BooleanField(verbose_name='TLSv1.2')),
                ('PFS', models.BooleanField(verbose_name='Any Forward Secrecy')),
                ('AFS', models.BooleanField(verbose_name='All Forward Secrecy')),
                ('DHGroup', models.CharField(max_length=500, verbose_name='Weakest DH Group Size')),
                ('anyRC4', models.BooleanField(verbose_name='Any RC4')),
                ('allRC4', models.BooleanField(verbose_name='All RC4')),
                ('tripleDES', models.BooleanField(verbose_name='Any 3DES')),
                ('keyType', models.CharField(max_length=500, verbose_name='Key Type')),
                ('keyLength', models.CharField(max_length=500, verbose_name='Key Length')),
                ('sigAlgo', models.CharField(max_length=500, verbose_name='Signature Algorithm')),
                ('shaServed', models.BooleanField(verbose_name='SHA-1 in Served Chain')),
                ('shaConstructed', models.BooleanField(verbose_name='SHA-1 in Constructed Chain')),
                ('notBefore', models.DateTimeField(verbose_name='Not Before')),
                ('notAfter', models.DateTimeField(verbose_name='Not After')),
                ('highestServedIssuer', models.CharField(max_length=500, verbose_name='Highest Served Issuer')),
                ('highestConstructedIssuer', models.CharField(max_length=500, verbose_name='Highest Constructed Issuer')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Domain')),
            ],
        ),
    ]
